title: Nguyen Tran
baseURL: 'https://example.com/'

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
hasCJKLanguage: false
removePathAccents: true

languages:
  en:
    languageName: "English"
    weight: 1
    contentDir: "content/en"
  vi:
    languageName: "Tiếng Việt"
    weight: 2
    contentDir: "content/vi"

build:
  writeStats: true

enableGitInfo: false
summaryLength: 30

pagination:
  pagerSize: 10

enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: "<sup>^</sup>"

ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$

permalinks:
  authors: '/author/:slug/'

disableAliases: true

outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart

timeout: 600000

taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types

markup:
  _merge: deep
  highlight:
    lineNos: false

security:
  _merge: deep

sitemap:
  _merge: deep
